codecov:
  token: 011b1477-c113-4944-9627-f3dc0dac7675

coverage:
  precision: 2
  round: down
  range: "90...100"

comment:
  layout: "header, diff, changes, sunburst, uncovered, tree"
  behavior: default
