sudo: false
language: elixir
matrix:
  include:
    - otp_release: 18.3
      elixir: 1.3.2
      script: mix test
    - otp_release: 19.0
      elixir: 1.3.2
      script: mix test
    - otp_release: 18.3
      elixir: 1.4.2
    - otp_release: 19.0
      elixir: 1.4.2
matrix:
  fast_finish: true
  allow_failures:
    - otp_release: 18.3
      elixir: 1.4.2
    - otp_release: 19.0
      elixir: 1.4.2
script:
- mix credo --strict
- mix dialyzer --halt-exit-status
- MIX_ENV=test mix do compile --warnings-as-errors, coveralls.json
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
