sudo: false
language: elixir
matrix:
  include:
    - otp_release: 18.3
      elixir: 1.3.2
    - otp_release: 19.0
      elixir: 1.3.2
env:
- MIX_ENV=test
script:
- mix do compile --warnings-as-errors, coveralls.json
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
