version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    environment:
      - DB_ENV_POSTGRES_HOST=db
    command: mix phx.server
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
