version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=localhost
      - POSTGRES_DB=web_test
  web:
    build: .
    command: mix phx.server
    environment:
      - MIX_ENV=test
      - DB_ENV_POSTGRES_USER=postgres
      - DB_ENV_POSTGRES_PASSWORD=postgres
      - DB_ENV_POSTGRES_HOST=127.0.0.1:5432
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
