version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=web_test
  web:
    build: .
    command: mix phx.server
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
