version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run: docker-compose build
      - run: docker-compose run web mix do deps.get, deps.compile
      - run: docker-compose up -d
      - run: sleep 1
      - run: docker-compose exec web mix do ecto.create, ecto.migrate
      - run: docker-compose run --rm -e "MIX_ENV=test" web mix test
      - run: docker-compose down
