name: Elixir CI

on: push

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: node:10.18-jessie

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
  build:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp: [22.2]
        elixir: [1.9.4]
    env:
      MIX_ENV: test

    steps:
      - uses: actions/checkout@v2
      - name: Setup elixir
        uses: actions/setup-elixir@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}

      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix do deps.get, deps.compile

      - run: mix format --check-formatted
      - run: mix credo --strict
      - run: mix do ecto.create, ecto.migrate
      - run: mix coveralls.json -u
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: cover/excoveralls.json
          fail_ci_if_error: true
