name: Elixir CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp: [22.1.7]
        elixir: [1.9.4]
    env:
      MIX_ENV: test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: harmon758/postgresql-action@v1
        with:
          postgresql version: "11" # See https://hub.docker.com/_/postgres for available versions

      - uses: actions/checkout@v2
      - name: Setup elixir
        uses: actions/setup-elixir@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - name: Get deps cache
        uses: actions/cache@v1
        with:
          path: deps/
          key: ${{ runner.os }}-deps-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-deps-

      - name: Get build cache
        uses: actions/cache@v1
        with:
          path: _build/test/
          key: ${{ runner.os }}-build-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-build-

      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
          mix compile

      - name: lint
        run: |
          mix format --check-formatted
          mix dialyzer
          mix credo --strict

      - name: migrate
        run: |
          mix ecto.create
          mix ecto.migrate

      - run: mix coveralls.github
